name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pack Zip
        run: |
          cd ${{ github.workspace }}/custom_components/ml_solar_forecast
          zip ml_solar_forecast.zip -r ./


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload the zip file as a release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "${{ github.workspace }}/custom_components/ml_solar_forecast/ml_solar_forecast.zip"
          asset_name: ml_solar_forecast.zip
          asset_content_type: application/zip

