name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update version in manifest.json and const.py from current git tag
        run: |
          sed -i "s/0\\.0\\.0\\.dev0/${GITHUB_REF_NAME}/g" custom_components/ml_solar_forecast/manifest.json
          sed -i "s/0\\.0\\.0\\.dev0/${GITHUB_REF_NAME}/g" custom_components/ml_solar_forecast/const.py

      - name: Pack Zip
        run: |
          cd ${{ github.workspace }}/custom_components/ml_solar_forecast
          zip ml_solar_forecast.zip -r ./


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/custom_components/ml_solar_forecast/ml_solar_forecast.zip

